name: fivec_notes
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_quill: ^9.3.8
  path: ^1.9.0
  sqflite: ^2.3.3
  file_picker:
  provider:
  mockito: ^5.4.4
  http:
  connectivity_plus: ^6.0.3
  shared_preferences: ^2.2.3
  flutter_quill_test: ^9.3.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/5cnotes-logo.png

